import {
  Activity,
  AlertTriangle,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUpRight,
  Banknote,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Car,
  ChevronRight,
  CircleDollarSign,
  CreditCard,
  Droplets,
  FileText,
  Flame,
  Gift,
  Globe,
  GraduationCap,
  HandCoins,
  Heart,
  HeartPulse,
  Home,
  Info,
  Landmark,
  LayoutDashboard,
  LineChart as LineChartIcon,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  Moon,
  MoreHorizontal,
  Package,
  Phone,
  PiggyBank,
  Plane,
  QrCode,
  Receipt,
  RefreshCw,
  Repeat,
  Scale,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShieldPlus,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Target,
  Ticket,
  TrendingUp,
  Tv,
  Umbrella,
  User,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-down-left': ArrowDownLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-up-right': ArrowUpRight,
  banknote: Banknote,
  bell: Bell,
  book: BookOpen,
  briefcase: Briefcase,
  building: Building2,
  calendar: Calendar,
  car: Car,
  'circle-dollar': CircleDollarSign,
  'credit-card': CreditCard,
  droplets: Droplets,
  file: FileText,
  flame: Flame,
  gift: Gift,
  globe: Globe,
  'graduation-cap': GraduationCap,
  'hand-coins': HandCoins,
  heart: Heart,
  'heart-pulse': HeartPulse,
  home: Home,
  info: Info,
  landmark: Landmark,
  dashboard: LayoutDashboard,
  chart: LineChartIcon,
  lock: Lock,
  mail: Mail,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  moon: Moon,
  more: MoreHorizontal,
  package: Package,
  phone: Phone,
  piggy: PiggyBank,
  plane: Plane,
  'qr-code': QrCode,
  receipt: Receipt,
  refresh: RefreshCw,
  repeat: Repeat,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-plus': ShieldPlus,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  target: Target,
  ticket: Ticket,
  'trending-up': TrendingUp,
  tv: Tv,
  umbrella: Umbrella,
  user: User,
  'user-cog': UserCog,
  'user-plus': UserPlus,
  users: Users,
  wallet: Wallet,
  wifi: Wifi,
  zap: Zap,
  cap: GraduationCap,
  scale: Scale,
  chevron: ChevronRight,
};

export type IconName = keyof typeof ICONS | string;

/**
 * Resolves a string name from the demo data layer into a lucide icon.
 * Falls back to a neutral glyph so unknown names never break a view.
 */
export function Icon({ name, className, strokeWidth = 2 }: { name: IconName; className?: string; strokeWidth?: number }) {
  const Cmp = ICONS[name] ?? Info;
  return <Cmp className={cn('h-5 w-5', className)} strokeWidth={strokeWidth} aria-hidden />;
}

export function iconExists(name: string): boolean {
  return name in ICONS;
}
